import type { Metadata } from "next"
import { Kanit } from "next/font/google"
import "@/css/globals.css"
import SessionProvider from "@/providers/SessionProvider"
import { getServerSession } from "next-auth"

//components
import Sidebar from "./components/sidebar"
import { CartProvider } from "@/context/CartContext"

const kanit = Kanit({
    subsets: ["thai", "latin"],
    weight: ["200", "300", "400", "500", "600"],
})

export const metadata: Metadata = {
    title: "POS-system",
    description: "Generated by 3Men",
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getServerSession()

    return (
        <html lang="th">
            <body
                className={`${kanit.className} antialiased bg-background text-night flex `}
            >
                <SessionProvider session={session}>
                    <CartProvider>
                        <Sidebar />
                        <div className="mx-5 mt-5 w-screen flex justify-center text-xl">{children}</div>
                    </CartProvider>
                </SessionProvider>
            </body>
        </html>
    )
}
